package com.medical.dao;

import com.medical.model.JzDisasterafter;
import com.medical.model.JzDisasterafterExample;
import java.math.BigDecimal;
import java.util.List;

public interface JzDisasterafterDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table YLJZN.JZ_DISASTERAFTER
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    int countByExample(JzDisasterafterExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table YLJZN.JZ_DISASTERAFTER
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    int deleteByExample(JzDisasterafterExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table YLJZN.JZ_DISASTERAFTER
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    int deleteByPrimaryKey(BigDecimal daId);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table YLJZN.JZ_DISASTERAFTER
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    BigDecimal insert(JzDisasterafter record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table YLJZN.JZ_DISASTERAFTER
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    BigDecimal insertSelective(JzDisasterafter record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table YLJZN.JZ_DISASTERAFTER
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    List<JzDisasterafter> selectByExample(JzDisasterafterExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table YLJZN.JZ_DISASTERAFTER
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    JzDisasterafter selectByPrimaryKey(BigDecimal daId);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table YLJZN.JZ_DISASTERAFTER
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    int updateByExampleSelective(JzDisasterafter record, JzDisasterafterExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table YLJZN.JZ_DISASTERAFTER
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    int updateByExample(JzDisasterafter record, JzDisasterafterExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table YLJZN.JZ_DISASTERAFTER
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    int updateByPrimaryKeySelective(JzDisasterafter record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table YLJZN.JZ_DISASTERAFTER
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    int updateByPrimaryKey(JzDisasterafter record);
}