package com.medical.dao;

import com.medical.model.JzDisasterafter;
import com.medical.model.JzDisasterafterExample;
import java.math.BigDecimal;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class JzDisasterafterDAOImpl extends SqlMapClientDaoSupport implements JzDisasterafterDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table YLJZN.JZ_DISASTERAFTER
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    public JzDisasterafterDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table YLJZN.JZ_DISASTERAFTER
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    public int countByExample(JzDisasterafterExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("JZ_DISASTERAFTER.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table YLJZN.JZ_DISASTERAFTER
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    public int deleteByExample(JzDisasterafterExample example) {
        int rows = getSqlMapClientTemplate().delete("JZ_DISASTERAFTER.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table YLJZN.JZ_DISASTERAFTER
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    public int deleteByPrimaryKey(BigDecimal daId) {
        JzDisasterafter key = new JzDisasterafter();
        key.setDaId(daId);
        int rows = getSqlMapClientTemplate().delete("JZ_DISASTERAFTER.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table YLJZN.JZ_DISASTERAFTER
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    public BigDecimal insert(JzDisasterafter record) {
        Object newKey = getSqlMapClientTemplate().insert("JZ_DISASTERAFTER.ibatorgenerated_insert", record);
        return (BigDecimal) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table YLJZN.JZ_DISASTERAFTER
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    public BigDecimal insertSelective(JzDisasterafter record) {
        Object newKey = getSqlMapClientTemplate().insert("JZ_DISASTERAFTER.ibatorgenerated_insertSelective", record);
        return (BigDecimal) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table YLJZN.JZ_DISASTERAFTER
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    @SuppressWarnings("unchecked")
    public List<JzDisasterafter> selectByExample(JzDisasterafterExample example) {
        List<JzDisasterafter> list = getSqlMapClientTemplate().queryForList("JZ_DISASTERAFTER.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table YLJZN.JZ_DISASTERAFTER
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    public JzDisasterafter selectByPrimaryKey(BigDecimal daId) {
        JzDisasterafter key = new JzDisasterafter();
        key.setDaId(daId);
        JzDisasterafter record = (JzDisasterafter) getSqlMapClientTemplate().queryForObject("JZ_DISASTERAFTER.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table YLJZN.JZ_DISASTERAFTER
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    public int updateByExampleSelective(JzDisasterafter record, JzDisasterafterExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("JZ_DISASTERAFTER.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table YLJZN.JZ_DISASTERAFTER
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    public int updateByExample(JzDisasterafter record, JzDisasterafterExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("JZ_DISASTERAFTER.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table YLJZN.JZ_DISASTERAFTER
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    public int updateByPrimaryKeySelective(JzDisasterafter record) {
        int rows = getSqlMapClientTemplate().update("JZ_DISASTERAFTER.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table YLJZN.JZ_DISASTERAFTER
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    public int updateByPrimaryKey(JzDisasterafter record) {
        int rows = getSqlMapClientTemplate().update("JZ_DISASTERAFTER.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table YLJZN.JZ_DISASTERAFTER
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    private static class UpdateByExampleParms extends JzDisasterafterExample {
        private Object record;

        public UpdateByExampleParms(Object record, JzDisasterafterExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}