package com.medical.dao;

import com.medical.model.JzMabills;
import com.medical.model.JzMabillsExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class JzMabillsDAOImpl extends SqlMapClientDaoSupport implements JzMabillsDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table YLJZN.JZ_MABILLS
     *
     * @ibatorgenerated Thu Dec 04 01:08:35 CST 2014
     */
    public JzMabillsDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table YLJZN.JZ_MABILLS
     *
     * @ibatorgenerated Thu Dec 04 01:08:35 CST 2014
     */
    public int countByExample(JzMabillsExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("JZ_MABILLS.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table YLJZN.JZ_MABILLS
     *
     * @ibatorgenerated Thu Dec 04 01:08:35 CST 2014
     */
    public int deleteByExample(JzMabillsExample example) {
        int rows = getSqlMapClientTemplate().delete("JZ_MABILLS.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table YLJZN.JZ_MABILLS
     *
     * @ibatorgenerated Thu Dec 04 01:08:35 CST 2014
     */
    public void insert(JzMabills record) {
        getSqlMapClientTemplate().insert("JZ_MABILLS.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table YLJZN.JZ_MABILLS
     *
     * @ibatorgenerated Thu Dec 04 01:08:35 CST 2014
     */
    public void insertSelective(JzMabills record) {
        getSqlMapClientTemplate().insert("JZ_MABILLS.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table YLJZN.JZ_MABILLS
     *
     * @ibatorgenerated Thu Dec 04 01:08:35 CST 2014
     */
    @SuppressWarnings("unchecked")
    public List<JzMabills> selectByExample(JzMabillsExample example) {
        List<JzMabills> list = getSqlMapClientTemplate().queryForList("JZ_MABILLS.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table YLJZN.JZ_MABILLS
     *
     * @ibatorgenerated Thu Dec 04 01:08:35 CST 2014
     */
    public int updateByExampleSelective(JzMabills record, JzMabillsExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("JZ_MABILLS.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table YLJZN.JZ_MABILLS
     *
     * @ibatorgenerated Thu Dec 04 01:08:35 CST 2014
     */
    public int updateByExample(JzMabills record, JzMabillsExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("JZ_MABILLS.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table YLJZN.JZ_MABILLS
     *
     * @ibatorgenerated Thu Dec 04 01:08:35 CST 2014
     */
    private static class UpdateByExampleParms extends JzMabillsExample {
        private Object record;

        public UpdateByExampleParms(Object record, JzMabillsExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}