package com.medical.dao;

import com.medical.model.JzMedicalafter;
import com.medical.model.JzMedicalafterExample;
import java.math.BigDecimal;
import java.util.List;

public interface JzMedicalafterDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table YLJZN.JZ_MEDICALAFTER
     *
     * @ibatorgenerated Tue Apr 07 11:20:30 CST 2015
     */
    int countByExample(JzMedicalafterExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table YLJZN.JZ_MEDICALAFTER
     *
     * @ibatorgenerated Tue Apr 07 11:20:30 CST 2015
     */
    int deleteByExample(JzMedicalafterExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table YLJZN.JZ_MEDICALAFTER
     *
     * @ibatorgenerated Tue Apr 07 11:20:30 CST 2015
     */
    int deleteByPrimaryKey(BigDecimal maId);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table YLJZN.JZ_MEDICALAFTER
     *
     * @ibatorgenerated Tue Apr 07 11:20:30 CST 2015
     */
    BigDecimal insert(JzMedicalafter record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table YLJZN.JZ_MEDICALAFTER
     *
     * @ibatorgenerated Tue Apr 07 11:20:30 CST 2015
     */
    BigDecimal insertSelective(JzMedicalafter record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table YLJZN.JZ_MEDICALAFTER
     *
     * @ibatorgenerated Tue Apr 07 11:20:30 CST 2015
     */
    List<JzMedicalafter> selectByExample(JzMedicalafterExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table YLJZN.JZ_MEDICALAFTER
     *
     * @ibatorgenerated Tue Apr 07 11:20:30 CST 2015
     */
    JzMedicalafter selectByPrimaryKey(BigDecimal maId);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table YLJZN.JZ_MEDICALAFTER
     *
     * @ibatorgenerated Tue Apr 07 11:20:30 CST 2015
     */
    int updateByExampleSelective(JzMedicalafter record, JzMedicalafterExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table YLJZN.JZ_MEDICALAFTER
     *
     * @ibatorgenerated Tue Apr 07 11:20:30 CST 2015
     */
    int updateByExample(JzMedicalafter record, JzMedicalafterExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table YLJZN.JZ_MEDICALAFTER
     *
     * @ibatorgenerated Tue Apr 07 11:20:30 CST 2015
     */
    int updateByPrimaryKeySelective(JzMedicalafter record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table YLJZN.JZ_MEDICALAFTER
     *
     * @ibatorgenerated Tue Apr 07 11:20:30 CST 2015
     */
    int updateByPrimaryKey(JzMedicalafter record);
}