package com.medical.dao;

import com.medical.model.MemberBaseinfo;
import com.medical.model.MemberBaseinfoExample;
import java.util.List;

public interface MemberBaseinfoDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table YLJZN.MEMBER_BASEINFO
     *
     * @ibatorgenerated Wed Nov 19 14:51:11 CST 2014
     */
    int countByExample(MemberBaseinfoExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table YLJZN.MEMBER_BASEINFO
     *
     * @ibatorgenerated Wed Nov 19 14:51:11 CST 2014
     */
    int deleteByExample(MemberBaseinfoExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table YLJZN.MEMBER_BASEINFO
     *
     * @ibatorgenerated Wed Nov 19 14:51:11 CST 2014
     */
    void insert(MemberBaseinfo record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table YLJZN.MEMBER_BASEINFO
     *
     * @ibatorgenerated Wed Nov 19 14:51:11 CST 2014
     */
    void insertSelective(MemberBaseinfo record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table YLJZN.MEMBER_BASEINFO
     *
     * @ibatorgenerated Wed Nov 19 14:51:11 CST 2014
     */
    List<MemberBaseinfo> selectByExampleWithBLOBs(MemberBaseinfoExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table YLJZN.MEMBER_BASEINFO
     *
     * @ibatorgenerated Wed Nov 19 14:51:11 CST 2014
     */
    List<MemberBaseinfo> selectByExampleWithoutBLOBs(MemberBaseinfoExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table YLJZN.MEMBER_BASEINFO
     *
     * @ibatorgenerated Wed Nov 19 14:51:11 CST 2014
     */
    int updateByExampleSelective(MemberBaseinfo record, MemberBaseinfoExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table YLJZN.MEMBER_BASEINFO
     *
     * @ibatorgenerated Wed Nov 19 14:51:11 CST 2014
     */
    int updateByExampleWithBLOBs(MemberBaseinfo record, MemberBaseinfoExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table YLJZN.MEMBER_BASEINFO
     *
     * @ibatorgenerated Wed Nov 19 14:51:11 CST 2014
     */
    int updateByExampleWithoutBLOBs(MemberBaseinfo record, MemberBaseinfoExample example);
    
	public List<MemberBaseinfo> selectByExampleWithoutBLOBs(MemberBaseinfoExample example,
			int skipResults, int maxResults);
}