package com.medical.model;

import java.math.BigDecimal;
import java.util.Date;

public class JzDisasterafter {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_DISASTERAFTER.DA_ID
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    private BigDecimal daId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_DISASTERAFTER.MEMBERNAME
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    private String membername;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_DISASTERAFTER.PAPERID
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    private String paperid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_DISASTERAFTER.SSN
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    private String ssn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_DISASTERAFTER.HOSPITAL
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    private String hospital;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_DISASTERAFTER.HOSPITALLEVEL
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    private String hospitallevel;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_DISASTERAFTER.SICKENCONTENT
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    private String sickencontent;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_DISASTERAFTER.BEGINTIME
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    private Date begintime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_DISASTERAFTER.ENDTIME
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    private Date endtime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_DISASTERAFTER.APPROVERESULT
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    private String approveresult;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_DISASTERAFTER.APPROVECONTENT
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    private String approvecontent;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_DISASTERAFTER.TOTALCOST
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    private BigDecimal totalcost;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_DISASTERAFTER.INSUREPAY
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    private BigDecimal insurepay;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_DISASTERAFTER.OUTPAY
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    private BigDecimal outpay;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_DISASTERAFTER.CAPAY
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    private BigDecimal capay;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_DISASTERAFTER.BUSINESSPAY
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    private BigDecimal businesspay;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_DISASTERAFTER.ASISSTPAY
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    private BigDecimal asisstpay;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_DISASTERAFTER.CREATETIME
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    private Date createtime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_DISASTERAFTER.UPDATETIME
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    private Date updatetime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_DISASTERAFTER.MEMBER_ID
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    private String memberId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_DISASTERAFTER.MEMBER_TYPE
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    private String memberType;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_DISASTERAFTER.IMPLSTS
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    private String implsts;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_DISASTERAFTER.TIKETNO
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    private String tiketno;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_DISASTERAFTER.MEDICALTYPE
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    private String medicaltype;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_DISASTERAFTER.INSURETYPE
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    private String insuretype;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_DISASTERAFTER.PERSONTYPE
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    private String persontype;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_DISASTERAFTER.ON_NO
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    private String onNo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_DISASTERAFTER.PAY_LINE
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    private BigDecimal payLine;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_DISASTERAFTER.HOSPITALPAY
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    private BigDecimal hospitalpay;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_DISASTERAFTER.DIAGNOSE
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    private String diagnose;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_DISASTERAFTER.FAMCOUNT
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    private Short famcount;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_DISASTERAFTER.FAMADDR
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    private String famaddr;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_DISASTERAFTER.TELEPHONE
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    private String telephone;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_DISASTERAFTER.SEX
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    private String sex;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_DISASTERAFTER.BIRTHDAY
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    private Date birthday;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_DISASTERAFTER.WSFLAG
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    private String wsflag;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_DISASTERAFTER.PZ_PRINUM
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    private Long pzPrinum;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_DISASTERAFTER.APP_PRINUM
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    private Long appPrinum;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_DISASTERAFTER.MASTERNAME
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    private String mastername;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_DISASTERAFTER.MASTERIDCARD
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    private String masteridcard;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_DISASTERAFTER.BANK_ACCOUNT
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    private String bankAccount;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_DISASTERAFTER.BANK_ACCOUNT1
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    private String bankAccount1;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_DISASTERAFTER.DA_ID
     *
     * @return the value of YLJZN.JZ_DISASTERAFTER.DA_ID
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    public BigDecimal getDaId() {
        return daId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_DISASTERAFTER.DA_ID
     *
     * @param daId the value for YLJZN.JZ_DISASTERAFTER.DA_ID
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    public void setDaId(BigDecimal daId) {
        this.daId = daId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_DISASTERAFTER.MEMBERNAME
     *
     * @return the value of YLJZN.JZ_DISASTERAFTER.MEMBERNAME
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    public String getMembername() {
        return membername;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_DISASTERAFTER.MEMBERNAME
     *
     * @param membername the value for YLJZN.JZ_DISASTERAFTER.MEMBERNAME
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    public void setMembername(String membername) {
        this.membername = membername;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_DISASTERAFTER.PAPERID
     *
     * @return the value of YLJZN.JZ_DISASTERAFTER.PAPERID
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    public String getPaperid() {
        return paperid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_DISASTERAFTER.PAPERID
     *
     * @param paperid the value for YLJZN.JZ_DISASTERAFTER.PAPERID
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    public void setPaperid(String paperid) {
        this.paperid = paperid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_DISASTERAFTER.SSN
     *
     * @return the value of YLJZN.JZ_DISASTERAFTER.SSN
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    public String getSsn() {
        return ssn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_DISASTERAFTER.SSN
     *
     * @param ssn the value for YLJZN.JZ_DISASTERAFTER.SSN
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    public void setSsn(String ssn) {
        this.ssn = ssn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_DISASTERAFTER.HOSPITAL
     *
     * @return the value of YLJZN.JZ_DISASTERAFTER.HOSPITAL
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    public String getHospital() {
        return hospital;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_DISASTERAFTER.HOSPITAL
     *
     * @param hospital the value for YLJZN.JZ_DISASTERAFTER.HOSPITAL
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    public void setHospital(String hospital) {
        this.hospital = hospital;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_DISASTERAFTER.HOSPITALLEVEL
     *
     * @return the value of YLJZN.JZ_DISASTERAFTER.HOSPITALLEVEL
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    public String getHospitallevel() {
        return hospitallevel;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_DISASTERAFTER.HOSPITALLEVEL
     *
     * @param hospitallevel the value for YLJZN.JZ_DISASTERAFTER.HOSPITALLEVEL
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    public void setHospitallevel(String hospitallevel) {
        this.hospitallevel = hospitallevel;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_DISASTERAFTER.SICKENCONTENT
     *
     * @return the value of YLJZN.JZ_DISASTERAFTER.SICKENCONTENT
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    public String getSickencontent() {
        return sickencontent;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_DISASTERAFTER.SICKENCONTENT
     *
     * @param sickencontent the value for YLJZN.JZ_DISASTERAFTER.SICKENCONTENT
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    public void setSickencontent(String sickencontent) {
        this.sickencontent = sickencontent;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_DISASTERAFTER.BEGINTIME
     *
     * @return the value of YLJZN.JZ_DISASTERAFTER.BEGINTIME
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    public Date getBegintime() {
        return begintime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_DISASTERAFTER.BEGINTIME
     *
     * @param begintime the value for YLJZN.JZ_DISASTERAFTER.BEGINTIME
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    public void setBegintime(Date begintime) {
        this.begintime = begintime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_DISASTERAFTER.ENDTIME
     *
     * @return the value of YLJZN.JZ_DISASTERAFTER.ENDTIME
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    public Date getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_DISASTERAFTER.ENDTIME
     *
     * @param endtime the value for YLJZN.JZ_DISASTERAFTER.ENDTIME
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_DISASTERAFTER.APPROVERESULT
     *
     * @return the value of YLJZN.JZ_DISASTERAFTER.APPROVERESULT
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    public String getApproveresult() {
        return approveresult;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_DISASTERAFTER.APPROVERESULT
     *
     * @param approveresult the value for YLJZN.JZ_DISASTERAFTER.APPROVERESULT
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    public void setApproveresult(String approveresult) {
        this.approveresult = approveresult;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_DISASTERAFTER.APPROVECONTENT
     *
     * @return the value of YLJZN.JZ_DISASTERAFTER.APPROVECONTENT
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    public String getApprovecontent() {
        return approvecontent;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_DISASTERAFTER.APPROVECONTENT
     *
     * @param approvecontent the value for YLJZN.JZ_DISASTERAFTER.APPROVECONTENT
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    public void setApprovecontent(String approvecontent) {
        this.approvecontent = approvecontent;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_DISASTERAFTER.TOTALCOST
     *
     * @return the value of YLJZN.JZ_DISASTERAFTER.TOTALCOST
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    public BigDecimal getTotalcost() {
        return totalcost;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_DISASTERAFTER.TOTALCOST
     *
     * @param totalcost the value for YLJZN.JZ_DISASTERAFTER.TOTALCOST
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    public void setTotalcost(BigDecimal totalcost) {
        this.totalcost = totalcost;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_DISASTERAFTER.INSUREPAY
     *
     * @return the value of YLJZN.JZ_DISASTERAFTER.INSUREPAY
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    public BigDecimal getInsurepay() {
        return insurepay;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_DISASTERAFTER.INSUREPAY
     *
     * @param insurepay the value for YLJZN.JZ_DISASTERAFTER.INSUREPAY
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    public void setInsurepay(BigDecimal insurepay) {
        this.insurepay = insurepay;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_DISASTERAFTER.OUTPAY
     *
     * @return the value of YLJZN.JZ_DISASTERAFTER.OUTPAY
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    public BigDecimal getOutpay() {
        return outpay;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_DISASTERAFTER.OUTPAY
     *
     * @param outpay the value for YLJZN.JZ_DISASTERAFTER.OUTPAY
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    public void setOutpay(BigDecimal outpay) {
        this.outpay = outpay;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_DISASTERAFTER.CAPAY
     *
     * @return the value of YLJZN.JZ_DISASTERAFTER.CAPAY
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    public BigDecimal getCapay() {
        return capay;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_DISASTERAFTER.CAPAY
     *
     * @param capay the value for YLJZN.JZ_DISASTERAFTER.CAPAY
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    public void setCapay(BigDecimal capay) {
        this.capay = capay;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_DISASTERAFTER.BUSINESSPAY
     *
     * @return the value of YLJZN.JZ_DISASTERAFTER.BUSINESSPAY
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    public BigDecimal getBusinesspay() {
        return businesspay;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_DISASTERAFTER.BUSINESSPAY
     *
     * @param businesspay the value for YLJZN.JZ_DISASTERAFTER.BUSINESSPAY
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    public void setBusinesspay(BigDecimal businesspay) {
        this.businesspay = businesspay;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_DISASTERAFTER.ASISSTPAY
     *
     * @return the value of YLJZN.JZ_DISASTERAFTER.ASISSTPAY
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    public BigDecimal getAsisstpay() {
        return asisstpay;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_DISASTERAFTER.ASISSTPAY
     *
     * @param asisstpay the value for YLJZN.JZ_DISASTERAFTER.ASISSTPAY
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    public void setAsisstpay(BigDecimal asisstpay) {
        this.asisstpay = asisstpay;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_DISASTERAFTER.CREATETIME
     *
     * @return the value of YLJZN.JZ_DISASTERAFTER.CREATETIME
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_DISASTERAFTER.CREATETIME
     *
     * @param createtime the value for YLJZN.JZ_DISASTERAFTER.CREATETIME
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_DISASTERAFTER.UPDATETIME
     *
     * @return the value of YLJZN.JZ_DISASTERAFTER.UPDATETIME
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_DISASTERAFTER.UPDATETIME
     *
     * @param updatetime the value for YLJZN.JZ_DISASTERAFTER.UPDATETIME
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_DISASTERAFTER.MEMBER_ID
     *
     * @return the value of YLJZN.JZ_DISASTERAFTER.MEMBER_ID
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    public String getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_DISASTERAFTER.MEMBER_ID
     *
     * @param memberId the value for YLJZN.JZ_DISASTERAFTER.MEMBER_ID
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    public void setMemberId(String memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_DISASTERAFTER.MEMBER_TYPE
     *
     * @return the value of YLJZN.JZ_DISASTERAFTER.MEMBER_TYPE
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    public String getMemberType() {
        return memberType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_DISASTERAFTER.MEMBER_TYPE
     *
     * @param memberType the value for YLJZN.JZ_DISASTERAFTER.MEMBER_TYPE
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    public void setMemberType(String memberType) {
        this.memberType = memberType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_DISASTERAFTER.IMPLSTS
     *
     * @return the value of YLJZN.JZ_DISASTERAFTER.IMPLSTS
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    public String getImplsts() {
        return implsts;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_DISASTERAFTER.IMPLSTS
     *
     * @param implsts the value for YLJZN.JZ_DISASTERAFTER.IMPLSTS
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    public void setImplsts(String implsts) {
        this.implsts = implsts;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_DISASTERAFTER.TIKETNO
     *
     * @return the value of YLJZN.JZ_DISASTERAFTER.TIKETNO
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    public String getTiketno() {
        return tiketno;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_DISASTERAFTER.TIKETNO
     *
     * @param tiketno the value for YLJZN.JZ_DISASTERAFTER.TIKETNO
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    public void setTiketno(String tiketno) {
        this.tiketno = tiketno;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_DISASTERAFTER.MEDICALTYPE
     *
     * @return the value of YLJZN.JZ_DISASTERAFTER.MEDICALTYPE
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    public String getMedicaltype() {
        return medicaltype;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_DISASTERAFTER.MEDICALTYPE
     *
     * @param medicaltype the value for YLJZN.JZ_DISASTERAFTER.MEDICALTYPE
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    public void setMedicaltype(String medicaltype) {
        this.medicaltype = medicaltype;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_DISASTERAFTER.INSURETYPE
     *
     * @return the value of YLJZN.JZ_DISASTERAFTER.INSURETYPE
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    public String getInsuretype() {
        return insuretype;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_DISASTERAFTER.INSURETYPE
     *
     * @param insuretype the value for YLJZN.JZ_DISASTERAFTER.INSURETYPE
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    public void setInsuretype(String insuretype) {
        this.insuretype = insuretype;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_DISASTERAFTER.PERSONTYPE
     *
     * @return the value of YLJZN.JZ_DISASTERAFTER.PERSONTYPE
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    public String getPersontype() {
        return persontype;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_DISASTERAFTER.PERSONTYPE
     *
     * @param persontype the value for YLJZN.JZ_DISASTERAFTER.PERSONTYPE
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    public void setPersontype(String persontype) {
        this.persontype = persontype;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_DISASTERAFTER.ON_NO
     *
     * @return the value of YLJZN.JZ_DISASTERAFTER.ON_NO
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    public String getOnNo() {
        return onNo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_DISASTERAFTER.ON_NO
     *
     * @param onNo the value for YLJZN.JZ_DISASTERAFTER.ON_NO
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    public void setOnNo(String onNo) {
        this.onNo = onNo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_DISASTERAFTER.PAY_LINE
     *
     * @return the value of YLJZN.JZ_DISASTERAFTER.PAY_LINE
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    public BigDecimal getPayLine() {
        return payLine;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_DISASTERAFTER.PAY_LINE
     *
     * @param payLine the value for YLJZN.JZ_DISASTERAFTER.PAY_LINE
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    public void setPayLine(BigDecimal payLine) {
        this.payLine = payLine;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_DISASTERAFTER.HOSPITALPAY
     *
     * @return the value of YLJZN.JZ_DISASTERAFTER.HOSPITALPAY
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    public BigDecimal getHospitalpay() {
        return hospitalpay;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_DISASTERAFTER.HOSPITALPAY
     *
     * @param hospitalpay the value for YLJZN.JZ_DISASTERAFTER.HOSPITALPAY
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    public void setHospitalpay(BigDecimal hospitalpay) {
        this.hospitalpay = hospitalpay;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_DISASTERAFTER.DIAGNOSE
     *
     * @return the value of YLJZN.JZ_DISASTERAFTER.DIAGNOSE
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    public String getDiagnose() {
        return diagnose;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_DISASTERAFTER.DIAGNOSE
     *
     * @param diagnose the value for YLJZN.JZ_DISASTERAFTER.DIAGNOSE
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    public void setDiagnose(String diagnose) {
        this.diagnose = diagnose;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_DISASTERAFTER.FAMCOUNT
     *
     * @return the value of YLJZN.JZ_DISASTERAFTER.FAMCOUNT
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    public Short getFamcount() {
        return famcount;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_DISASTERAFTER.FAMCOUNT
     *
     * @param famcount the value for YLJZN.JZ_DISASTERAFTER.FAMCOUNT
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    public void setFamcount(Short famcount) {
        this.famcount = famcount;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_DISASTERAFTER.FAMADDR
     *
     * @return the value of YLJZN.JZ_DISASTERAFTER.FAMADDR
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    public String getFamaddr() {
        return famaddr;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_DISASTERAFTER.FAMADDR
     *
     * @param famaddr the value for YLJZN.JZ_DISASTERAFTER.FAMADDR
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    public void setFamaddr(String famaddr) {
        this.famaddr = famaddr;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_DISASTERAFTER.TELEPHONE
     *
     * @return the value of YLJZN.JZ_DISASTERAFTER.TELEPHONE
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_DISASTERAFTER.TELEPHONE
     *
     * @param telephone the value for YLJZN.JZ_DISASTERAFTER.TELEPHONE
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_DISASTERAFTER.SEX
     *
     * @return the value of YLJZN.JZ_DISASTERAFTER.SEX
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_DISASTERAFTER.SEX
     *
     * @param sex the value for YLJZN.JZ_DISASTERAFTER.SEX
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_DISASTERAFTER.BIRTHDAY
     *
     * @return the value of YLJZN.JZ_DISASTERAFTER.BIRTHDAY
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_DISASTERAFTER.BIRTHDAY
     *
     * @param birthday the value for YLJZN.JZ_DISASTERAFTER.BIRTHDAY
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_DISASTERAFTER.WSFLAG
     *
     * @return the value of YLJZN.JZ_DISASTERAFTER.WSFLAG
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    public String getWsflag() {
        return wsflag;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_DISASTERAFTER.WSFLAG
     *
     * @param wsflag the value for YLJZN.JZ_DISASTERAFTER.WSFLAG
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    public void setWsflag(String wsflag) {
        this.wsflag = wsflag;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_DISASTERAFTER.PZ_PRINUM
     *
     * @return the value of YLJZN.JZ_DISASTERAFTER.PZ_PRINUM
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    public Long getPzPrinum() {
        return pzPrinum;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_DISASTERAFTER.PZ_PRINUM
     *
     * @param pzPrinum the value for YLJZN.JZ_DISASTERAFTER.PZ_PRINUM
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    public void setPzPrinum(Long pzPrinum) {
        this.pzPrinum = pzPrinum;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_DISASTERAFTER.APP_PRINUM
     *
     * @return the value of YLJZN.JZ_DISASTERAFTER.APP_PRINUM
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    public Long getAppPrinum() {
        return appPrinum;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_DISASTERAFTER.APP_PRINUM
     *
     * @param appPrinum the value for YLJZN.JZ_DISASTERAFTER.APP_PRINUM
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    public void setAppPrinum(Long appPrinum) {
        this.appPrinum = appPrinum;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_DISASTERAFTER.MASTERNAME
     *
     * @return the value of YLJZN.JZ_DISASTERAFTER.MASTERNAME
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    public String getMastername() {
        return mastername;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_DISASTERAFTER.MASTERNAME
     *
     * @param mastername the value for YLJZN.JZ_DISASTERAFTER.MASTERNAME
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    public void setMastername(String mastername) {
        this.mastername = mastername;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_DISASTERAFTER.MASTERIDCARD
     *
     * @return the value of YLJZN.JZ_DISASTERAFTER.MASTERIDCARD
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    public String getMasteridcard() {
        return masteridcard;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_DISASTERAFTER.MASTERIDCARD
     *
     * @param masteridcard the value for YLJZN.JZ_DISASTERAFTER.MASTERIDCARD
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    public void setMasteridcard(String masteridcard) {
        this.masteridcard = masteridcard;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_DISASTERAFTER.BANK_ACCOUNT
     *
     * @return the value of YLJZN.JZ_DISASTERAFTER.BANK_ACCOUNT
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    public String getBankAccount() {
        return bankAccount;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_DISASTERAFTER.BANK_ACCOUNT
     *
     * @param bankAccount the value for YLJZN.JZ_DISASTERAFTER.BANK_ACCOUNT
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    public void setBankAccount(String bankAccount) {
        this.bankAccount = bankAccount;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_DISASTERAFTER.BANK_ACCOUNT1
     *
     * @return the value of YLJZN.JZ_DISASTERAFTER.BANK_ACCOUNT1
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    public String getBankAccount1() {
        return bankAccount1;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_DISASTERAFTER.BANK_ACCOUNT1
     *
     * @param bankAccount1 the value for YLJZN.JZ_DISASTERAFTER.BANK_ACCOUNT1
     *
     * @ibatorgenerated Mon Feb 02 15:36:04 CST 2015
     */
    public void setBankAccount1(String bankAccount1) {
        this.bankAccount1 = bankAccount1;
    }
}