package com.medical.model;

import java.math.BigDecimal;
import java.util.Date;

public class JzMabills {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_MABILLS.BILL_ID
     *
     * @ibatorgenerated Mon Dec 08 11:57:25 CST 2014
     */
    private Long billId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_MABILLS.MA_ID
     *
     * @ibatorgenerated Mon Dec 08 11:57:25 CST 2014
     */
    private Long maId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_MABILLS.FAMILYNO
     *
     * @ibatorgenerated Mon Dec 08 11:57:25 CST 2014
     */
    private String familyno;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_MABILLS.MEMBERNAME
     *
     * @ibatorgenerated Mon Dec 08 11:57:25 CST 2014
     */
    private String membername;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_MABILLS.PAPERID
     *
     * @ibatorgenerated Mon Dec 08 11:57:25 CST 2014
     */
    private String paperid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_MABILLS.CTIME
     *
     * @ibatorgenerated Mon Dec 08 11:57:25 CST 2014
     */
    private Date ctime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_MABILLS.UTIME
     *
     * @ibatorgenerated Mon Dec 08 11:57:25 CST 2014
     */
    private Date utime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_MABILLS.ASSISPAY
     *
     * @ibatorgenerated Mon Dec 08 11:57:25 CST 2014
     */
    private BigDecimal assispay;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_MABILLS.DS
     *
     * @ibatorgenerated Mon Dec 08 11:57:25 CST 2014
     */
    private String ds;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_MABILLS.SB_ID
     *
     * @ibatorgenerated Mon Dec 08 11:57:25 CST 2014
     */
    private String sbId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_MABILLS.BATCHNAME
     *
     * @ibatorgenerated Mon Dec 08 11:57:25 CST 2014
     */
    private String batchname;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_MABILLS.MASTERNAME
     *
     * @ibatorgenerated Mon Dec 08 11:57:25 CST 2014
     */
    private String mastername;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_MABILLS.MASTERIDCARD
     *
     * @ibatorgenerated Mon Dec 08 11:57:25 CST 2014
     */
    private String masteridcard;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_MABILLS.BANK_ACCOUNT
     *
     * @ibatorgenerated Mon Dec 08 11:57:25 CST 2014
     */
    private String bankAccount;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_MABILLS.BILL_ID
     *
     * @return the value of YLJZN.JZ_MABILLS.BILL_ID
     *
     * @ibatorgenerated Mon Dec 08 11:57:25 CST 2014
     */
    public Long getBillId() {
        return billId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_MABILLS.BILL_ID
     *
     * @param billId the value for YLJZN.JZ_MABILLS.BILL_ID
     *
     * @ibatorgenerated Mon Dec 08 11:57:25 CST 2014
     */
    public void setBillId(Long billId) {
        this.billId = billId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_MABILLS.MA_ID
     *
     * @return the value of YLJZN.JZ_MABILLS.MA_ID
     *
     * @ibatorgenerated Mon Dec 08 11:57:25 CST 2014
     */
    public Long getMaId() {
        return maId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_MABILLS.MA_ID
     *
     * @param maId the value for YLJZN.JZ_MABILLS.MA_ID
     *
     * @ibatorgenerated Mon Dec 08 11:57:25 CST 2014
     */
    public void setMaId(Long maId) {
        this.maId = maId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_MABILLS.FAMILYNO
     *
     * @return the value of YLJZN.JZ_MABILLS.FAMILYNO
     *
     * @ibatorgenerated Mon Dec 08 11:57:25 CST 2014
     */
    public String getFamilyno() {
        return familyno;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_MABILLS.FAMILYNO
     *
     * @param familyno the value for YLJZN.JZ_MABILLS.FAMILYNO
     *
     * @ibatorgenerated Mon Dec 08 11:57:25 CST 2014
     */
    public void setFamilyno(String familyno) {
        this.familyno = familyno;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_MABILLS.MEMBERNAME
     *
     * @return the value of YLJZN.JZ_MABILLS.MEMBERNAME
     *
     * @ibatorgenerated Mon Dec 08 11:57:25 CST 2014
     */
    public String getMembername() {
        return membername;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_MABILLS.MEMBERNAME
     *
     * @param membername the value for YLJZN.JZ_MABILLS.MEMBERNAME
     *
     * @ibatorgenerated Mon Dec 08 11:57:25 CST 2014
     */
    public void setMembername(String membername) {
        this.membername = membername;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_MABILLS.PAPERID
     *
     * @return the value of YLJZN.JZ_MABILLS.PAPERID
     *
     * @ibatorgenerated Mon Dec 08 11:57:25 CST 2014
     */
    public String getPaperid() {
        return paperid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_MABILLS.PAPERID
     *
     * @param paperid the value for YLJZN.JZ_MABILLS.PAPERID
     *
     * @ibatorgenerated Mon Dec 08 11:57:25 CST 2014
     */
    public void setPaperid(String paperid) {
        this.paperid = paperid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_MABILLS.CTIME
     *
     * @return the value of YLJZN.JZ_MABILLS.CTIME
     *
     * @ibatorgenerated Mon Dec 08 11:57:25 CST 2014
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_MABILLS.CTIME
     *
     * @param ctime the value for YLJZN.JZ_MABILLS.CTIME
     *
     * @ibatorgenerated Mon Dec 08 11:57:25 CST 2014
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_MABILLS.UTIME
     *
     * @return the value of YLJZN.JZ_MABILLS.UTIME
     *
     * @ibatorgenerated Mon Dec 08 11:57:25 CST 2014
     */
    public Date getUtime() {
        return utime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_MABILLS.UTIME
     *
     * @param utime the value for YLJZN.JZ_MABILLS.UTIME
     *
     * @ibatorgenerated Mon Dec 08 11:57:25 CST 2014
     */
    public void setUtime(Date utime) {
        this.utime = utime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_MABILLS.ASSISPAY
     *
     * @return the value of YLJZN.JZ_MABILLS.ASSISPAY
     *
     * @ibatorgenerated Mon Dec 08 11:57:25 CST 2014
     */
    public BigDecimal getAssispay() {
        return assispay;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_MABILLS.ASSISPAY
     *
     * @param assispay the value for YLJZN.JZ_MABILLS.ASSISPAY
     *
     * @ibatorgenerated Mon Dec 08 11:57:25 CST 2014
     */
    public void setAssispay(BigDecimal assispay) {
        this.assispay = assispay;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_MABILLS.DS
     *
     * @return the value of YLJZN.JZ_MABILLS.DS
     *
     * @ibatorgenerated Mon Dec 08 11:57:25 CST 2014
     */
    public String getDs() {
        return ds;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_MABILLS.DS
     *
     * @param ds the value for YLJZN.JZ_MABILLS.DS
     *
     * @ibatorgenerated Mon Dec 08 11:57:25 CST 2014
     */
    public void setDs(String ds) {
        this.ds = ds;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_MABILLS.SB_ID
     *
     * @return the value of YLJZN.JZ_MABILLS.SB_ID
     *
     * @ibatorgenerated Mon Dec 08 11:57:25 CST 2014
     */
    public String getSbId() {
        return sbId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_MABILLS.SB_ID
     *
     * @param sbId the value for YLJZN.JZ_MABILLS.SB_ID
     *
     * @ibatorgenerated Mon Dec 08 11:57:25 CST 2014
     */
    public void setSbId(String sbId) {
        this.sbId = sbId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_MABILLS.BATCHNAME
     *
     * @return the value of YLJZN.JZ_MABILLS.BATCHNAME
     *
     * @ibatorgenerated Mon Dec 08 11:57:25 CST 2014
     */
    public String getBatchname() {
        return batchname;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_MABILLS.BATCHNAME
     *
     * @param batchname the value for YLJZN.JZ_MABILLS.BATCHNAME
     *
     * @ibatorgenerated Mon Dec 08 11:57:25 CST 2014
     */
    public void setBatchname(String batchname) {
        this.batchname = batchname;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_MABILLS.MASTERNAME
     *
     * @return the value of YLJZN.JZ_MABILLS.MASTERNAME
     *
     * @ibatorgenerated Mon Dec 08 11:57:25 CST 2014
     */
    public String getMastername() {
        return mastername;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_MABILLS.MASTERNAME
     *
     * @param mastername the value for YLJZN.JZ_MABILLS.MASTERNAME
     *
     * @ibatorgenerated Mon Dec 08 11:57:25 CST 2014
     */
    public void setMastername(String mastername) {
        this.mastername = mastername;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_MABILLS.MASTERIDCARD
     *
     * @return the value of YLJZN.JZ_MABILLS.MASTERIDCARD
     *
     * @ibatorgenerated Mon Dec 08 11:57:25 CST 2014
     */
    public String getMasteridcard() {
        return masteridcard;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_MABILLS.MASTERIDCARD
     *
     * @param masteridcard the value for YLJZN.JZ_MABILLS.MASTERIDCARD
     *
     * @ibatorgenerated Mon Dec 08 11:57:25 CST 2014
     */
    public void setMasteridcard(String masteridcard) {
        this.masteridcard = masteridcard;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_MABILLS.BANK_ACCOUNT
     *
     * @return the value of YLJZN.JZ_MABILLS.BANK_ACCOUNT
     *
     * @ibatorgenerated Mon Dec 08 11:57:25 CST 2014
     */
    public String getBankAccount() {
        return bankAccount;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_MABILLS.BANK_ACCOUNT
     *
     * @param bankAccount the value for YLJZN.JZ_MABILLS.BANK_ACCOUNT
     *
     * @ibatorgenerated Mon Dec 08 11:57:25 CST 2014
     */
    public void setBankAccount(String bankAccount) {
        this.bankAccount = bankAccount;
    }
}